### ISSUE TITLE
Is this the repository ROS driver is released from?

### ISSUE THREAD

**Issue by 130s** [warp1337/rosleapmotion#4]
Wiki page of ROS driver `leap_motion` (http://wiki.ros.org/leap_motion) contains no info for the package upstream repository. I assume here (https://github.com/warp1337/rosleapmotion) is the one? Or here (https://github.com/ros-drivers/leap_motion)?

(Either way, the latest commit might not have been applied to the released version too).

**Comment by 130s** [comment]
Poke @warp1337 @mirzashah

**Comment by warp1337** [comment]
We need to push this (updated) repo into ros-drivers

**Comment by warp1337** [comment]
When I have merged the skeleton feature (see pull request) @mirzashah, would you do that?

**Comment by mirzashah** [comment]
@130s @warp1337 Yikes it's been a while since I've looked at this. When I released the package, I believe we used warp1337/rosleapmotion for upstream repo and gbp repo is https://github.com/ros-gbp/rosleapmotion-release. Chad had made a repo for us at ros-drivers/leap_motion which is what we should be using instead as the upstream.

So Florian, go ahead and create your pull request and I'll merge it. Once it's merged, we're going to have to rerun bloom to rerelease the package. I'll keep an eye out. I'll do a rerelease with the repo Chad created instead.

**Comment by 130s** [comment]
@mirzashah Looks like the pull request @warp1337 [was talking about](https://github.com/warp1337/rosleapmotion/pull/6) is merged already.

**Comment by mirzashah** [comment]
@130s Ah I see it...wow that's a great upgrade. I'll merge it into mainline. We definitely need to release this. Sorry I'm swamped these days and I'll have to get reacquainted with bloom. Thanks Isaac.

**Comment by 130s** [comment]
Thanks @mirzashah, I also opened [a PReq](https://github.com/ros-drivers/leap_motion/pull/2) to address this ticket. Closing.

**Comment by 130s** [comment]
Reopening. 

> Chad had made a repo for us at ros-drivers/leap_motion which is what we should be using instead as the upstream.

Can you move the default repo to `ros-drivers/leap_motion` @warp1337  @mirzashah ? And if possible give me write access so that I can take a new release role (there's been sufficient amount of commits since the last version). Thanks!

**Comment by 130s** [comment]
Thanks @mirzashah for adding me to the org. I'll make a new release from there soon.

**Comment by mirzashah** [comment]
@130s You should have access now...thanks for doing the release.
